import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';

const base = process.env.KRUG_BASE_URL || 'http://127.0.0.1:8787';
const credentialsPath = process.env.KRUG_CREDENTIALS || resolve(import.meta.dirname, '../artifacts/demo-credentials-local.txt');
const credentials = Object.fromEntries((await readFile(credentialsPath, 'utf8')).trim().split('\n').map(line => {
  const [role, value] = line.split(': ');
  const [email, password] = value.split(' / ');
  return [role, { email, password }];
}));
async function call(path, method = 'GET', body, cookie) {
  const response = await fetch(`${base}${path}`, { method, headers: { ...(body ? { 'Content-Type': 'application/json', Origin: base } : {}), ...(cookie ? { Cookie: cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json();
  return { status: response.status, data, cookie: response.headers.get('set-cookie')?.split(';')[0] };
}
const health = await call('/api/health');
assert.equal(health.status, 200);
assert.equal(health.data.database, 'ready');
const menu = await call('/api/menu');
assert.equal(menu.data.categories.length, 4);
assert.equal(menu.data.items.length, 18);
const noAuth = await call('/api/orders');
assert.equal(noAuth.status, 401);
const login = await call('/api/auth/login', 'POST', credentials.customer);
assert.equal(login.status, 200, JSON.stringify(login.data));
const customerCookie = login.cookie;
const cappuccino = menu.data.items.find(item => item.id === 'coffee-cappuccino');
const key = randomUUID();
const payload = { idempotencyKey: key, fulfillmentType: 'dine_in', tableNumber: '5', items: [{ id: cappuccino.id, quantity: 2 }] };
const created = await call('/api/orders', 'POST', payload, customerCookie);
assert.equal(created.status, 201, JSON.stringify(created.data));
assert.equal(created.data.order.total_kopeks, cappuccino.price_kopeks * 2);
const duplicate = await call('/api/orders', 'POST', payload, customerCookie);
assert.equal(duplicate.data.order.id, created.data.order.id);
const decline = await call(`/api/orders/${created.data.order.id}/mock-payment`, 'POST', { testCard: '0000 0000 0000 0002', requestId: randomUUID() }, customerCookie);
assert.equal(decline.data.order.payment_status, 'declined');
const paid = await call(`/api/orders/${created.data.order.id}/mock-payment`, 'POST', { testCard: '0000 0000 0000 0001', requestId: randomUUID() }, customerCookie);
assert.equal(paid.data.order.payment_status, 'simulated_paid');
assert.equal(paid.data.order.status, 'new');
const another = await call('/api/orders', 'GET', undefined, customerCookie);
assert.equal(another.data.orders[0].items[0].name_snapshot, 'Капучино');
const staffLogin = await call('/api/auth/login', 'POST', credentials.staff);
assert.equal(staffLogin.status, 200, JSON.stringify(staffLogin.data));
const blocked = await call('/api/staff/orders', 'GET', undefined, staffLogin.cookie);
assert.equal(blocked.status, 403);
const newStaffPassword = `${randomUUID()}Aa1!`;
const change = await call('/api/auth/change-password', 'POST', { oldPassword: credentials.staff.password, newPassword: newStaffPassword }, staffLogin.cookie);
assert.equal(change.status, 200);
const staffAgain = await call('/api/auth/login', 'POST', { email: credentials.staff.email, password: newStaffPassword });
assert.equal(staffAgain.status, 200);
const queue = await call('/api/staff/orders', 'GET', undefined, staffAgain.cookie);
assert.ok(queue.data.orders.some(order => order.id === created.data.order.id));
const prepare = await call(`/api/staff/orders/${created.data.order.id}`, 'PATCH', { status: 'preparing' }, staffAgain.cookie);
assert.equal(prepare.data.order.status, 'preparing');
const forbidden = await call('/api/admin/menu', 'GET', undefined, staffAgain.cookie);
assert.equal(forbidden.status, 403);
console.info(`Smoke passed at ${base}: menu, auth, idempotent order, test payment, roles and status.`);
